version: '2'
services:
  config:
    build: ./config/
    restart: always
    networks:
     - back
    ports:
     - "8888:8888"
  annuaire:
    build: ./annuaire/
    networks:
     - back
    ports:
     - "1111:1111"
    restart: always
    depends_on:
      - config
  delivery-service:
    build: ./delivery-service/
    networks:
     - back
    restart: always
    depends_on:
      - config
  notification-service:
    build: ./notification-service/
    networks:
     - back
    restart: always
    depends_on:
      - config
  orders-service:
    build: ./members/
    networks:
      - back
    restart: always
    depends_on:
      - config
  turbine:
    build: ./turbine/
    networks:
      - back
    restart: always
    depends_on:
      - config
    ports:
     - "5555:5555"
  gateway:
    build: ./proxy/
    networks:
      - front
      - back
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - config


networks:
  back:
  front:
